title: Alisha Sarfani
logo: /images/assets/Alisha-6991.jpg
description: Aspiring Data Analyst | MS Applied Analytics | Saint Louis University | Research Development Intern | Graduate Assistant
show_downloads: true
theme: jekyll-theme-minimal
